# general
background = '#24273a'
border_fg = '#494d64'
text_fg = '#cad3f5'
dimmed_text_fg = '#6e738d'
# input
input_text_fg = '#c6a0f6'
result_count_fg = '#c6a0f6'
# results
result_name_fg = '#8aadf4'
result_line_number_fg = '#eed49f'
result_value_fg = '#b7bdf8'
selection_fg = '#a6da95'
selection_bg = '#363a4f'
match_fg = '#a6da95'
# preview
preview_title_fg = '#c6a0f6'
# modes
channel_mode_fg = '#24273a'
channel_mode_bg = '#c6a0f6'
remote_control_mode_fg = '#24273a'
remote_control_mode_bg = '#a6da95'
